WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1
    FROM HOURS
    WHERE H < 23
)

SELECT 
    H AS HOUR,
    COUNT(A.DATETIME) AS COUNT
FROM HOURS
LEFT JOIN ANIMAL_OUTS A
    ON HOUR(A.DATETIME) = H
GROUP BY H
ORDER BY H;