SELECT YEAR (DIFFERENTIATION_DATE) AS YEAR, SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
    JOIN (
        SELECT YEAR (DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
        FROM ECOLI_DATA
        GROUP BY
            YEAR (DIFFERENTIATION_DATE)
    ) M ON YEAR (E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV