SELECT info.ID, name.FISH_NAME, info.LENGTH
FROM FISH_INFO AS info JOIN FISH_NAME_INFO AS name ON info.FISH_TYPE = name.FISH_TYPE
WHERE (info.FISH_TYPE, info.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY info.ID
