-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(
        CAR.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR CAR
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON CAR.CAR_TYPE = DP.CAR_TYPE
WHERE
    CAR.CAR_TYPE IN ('세단', 'SUV')
    AND DP.DURATION_TYPE = '30일 이상'
    AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
    AND ROUND(
        CAR.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)
    ) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;